# -*- coding: utf-8 -*-
"""Digital_twin_new (9).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OKTseO8TCDCLpmhv932ItfVDjrUYm7y5
"""

# # # import libraries

import pandas as pd
import gzip
import pickle
import math
import csv

import tracemalloc
import psutil
import os
import time

import tensorflow as tf
import numpy as np
import pandas as pd
from tensorflow import keras
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import time
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, mean_squared_error, r2_score, confusion_matrix



from google.colab import drive
drive.mount('/content/drive')

# # # # # # # Preprocessing from large dataset to clean dataset # # # # #


# # # # Load dataset

# df = pd.read_csv('/content/drive/MyDrive/dataset/digital_twin/dataset_large.csv')

# # Drop rows with NaN values in any column
# df = df.dropna()

# # # # # # # Preprocessing from large dataset to clean dataset # # # # #

# # # # Preprocessing data set

# # Remove unnecessary columns
# columns_to_remove = ['v_Acc','Movement','Global_X','Global_Y']
# df = df.drop(columns_to_remove, axis=1)

# df = pd.DataFrame(df)

# print(df.head(10))

# # # # # Preprocessing from large dataset to clean dataset # # # # #
df = pd.read_csv('/content/drive/MyDrive/labtest/vehicle_data.csv')
df = pd.DataFrame(df)

# Add Global_Time column
df['Global_Time'] = range(1, len(df) + 1)

# Count the number of vehicle
number_of_vehicle  = 100
# print(number_of_vehicle)

# Add the "Label" to identify the trusted and unstrusted vehicle, 1 is trusted
df['label'] = 1
df['trust_score'] = 100

# # # # # # Convert the direction to heading angle

# Define the mapping dictionary
mapping = {1: 90, 2: 180, 3: 270, 4: 360}

# Apply the mapping to the column using the map() function
df['Direction'] = df['Direction'].map(mapping)

# # ##  # # ## # ## #  Select the number of vehicle # # # ## # # # #

# # Parameters
# number_of_vehicle_exp = 100 # Max: 1680

# # # # # Modifying the number of vehicle # # # #

# # Get the list of unique Vehicle_IDs
# unique_ids = df['Vehicle_ID'].unique()

# # Calculate the number of extra unique Vehicle_IDs to remove
# extra_count = len(unique_ids) - number_of_vehicle_exp

# # Randomly select 'extra_count' unique Vehicle_IDs to remove
# ids_to_remove = np.random.choice(unique_ids, size=extra_count, replace=False)

# # Filter the DataFrame to keep only the desired Vehicle_IDs
# df = df[~df['Vehicle_ID'].isin(ids_to_remove)]

# number_of_vehicle  = df['Vehicle_ID'].nunique()
# print("The total vehicle:", number_of_vehicle)

# Sort the dataframe by 'Global_Time'
df = df.sort_values(by=['Vehicle_ID', 'Global_Time'])

# Calculate the time difference for each 'Vehicle_ID'
df['T'] = df.groupby('Vehicle_ID')['Global_Time'].shift(-1) - df['Global_Time']
df['T'] = df['T']*0.001 # change from milisecond -> seconds

# Save the clean dataset to a CSV file
df.to_csv('/content/drive/MyDrive/labtest/vehicle_data_full.csv', index=False)

# # # # # LOAD NEW DATASET # # # #

# # # # Load dataset

# df = pd.read_csv('/content/drive/MyDrive/dataset/digital_twin/final_clean_dataset_1680.csv')
df = pd.read_csv('/content/drive/MyDrive/labtest/vehicle_data_full.csv')

# # Select the number of data samples
# df = df.head(200000)

df = pd.DataFrame(df)

# Group by 'Vehicle_ID' and extract the first 100 rows for each group
df = df.groupby('Vehicle_ID').head(100)

# Print the total rows and the number of unique 'Vehicle_ID'
unique_vehicle_ids = df['Vehicle_ID'].nunique()
print("The total vehicle:", unique_vehicle_ids)

# # Filteer the DataFrame to get only the rows where 'Vehicle_ID' is 4
# df = df[df['Vehicle_ID'] == 4]

# Reset the index to the default integer index
df.set_index('Vehicle_ID', inplace=True)
df.reset_index(inplace=True)

# Parameters
epsilon = 1 #
desired_snr_dB = 30  # Desired SNR in dB
trust_score_threshold = 85
penalty_point = 5
percentage_of_untrusted_vehicle = 10

# # # supported Parameters
Gaussian_percentage = 20
epsilon_original = epsilon

# Count the number of vehicle
number_of_vehicle  = df['Vehicle_ID'].nunique()
print("The total vehicle:", number_of_vehicle)

number_of_untrusted_vehicles = int(percentage_of_untrusted_vehicle/100 * number_of_vehicle)

# # # # Configuring the unstrusted nodes

# # # # Load database of unstrusted nodes

# # untrust_df = pd.read_csv('/content/drive/MyDrive/dataset/digital_twin/save_30_percentage_untrusted_vehicles.csv')
# untrust_df = pd.read_csv('/content/drive/MyDrive/labtest/vehicle_data.csv')


# untrust_df = pd.DataFrame(untrust_df)

# # Select the first 100 elements from the DataFrame column
# selected_column = untrust_df['anomalies_ID'].head(number_of_untrusted_vehicles)

# # Convert the selected column to a NumPy array
# array_id_vehicle_anomalies = selected_column.values

# # Set the label to 0 for rows where vehicle_id matches the values in the array_id_vehicle_anomalies
# df.loc[df['Vehicle_ID'].isin(array_id_vehicle_anomalies), 'label'] = 0

# NEW
# Load database of untrusted nodes
untrust_df = pd.read_csv('/content/drive/MyDrive/labtest/vehicle_data.csv')
untrust_df = pd.DataFrame(untrust_df)

# Select the first 'number_of_untrusted_vehicles' elements from the DataFrame column
selected_column = untrust_df['Vehicle_ID'].head(number_of_untrusted_vehicles)

# Convert the selected column to a NumPy array
array_id_vehicle_anomalies = selected_column.values

# Set the label to 0 for rows where Vehicle_ID matches the values in the array_id_vehicle_anomalies
df.loc[df['Vehicle_ID'].isin(array_id_vehicle_anomalies), 'label'] = 0

# Calculate the standard deviation as a percentage of the column values
noise = df.loc[df['label'] == 0, 'Local_X'] * Gaussian_percentage
noise1 = df.loc[df['label'] == 0, 'Local_Y'] * Gaussian_percentage

# Add the noise to column
df.loc[df['label'] == 0, 'Local_X'] += np.abs(noise)
df.loc[df['label'] == 0, 'Local_Y'] += np.abs(noise1)

noiseSNR = epsilon/(math.pow(10, (desired_snr_dB/20)))

print(noiseSNR)

print(df.head(10))

# Calculate the X_estimate and Y_estimate

# equation (3)
def calculate_Xestimate(X_tB,S_tB,H_tB,T):
  return X_tB + S_tB*T*np.sin(np.radians(H_tB))

# equation (4)
def calculate_Yestimate(Y_tB,S_tB,H_tB,T):
  return Y_tB + S_tB*T*np.cos(np.radians(H_tB))


# Start time
start_time1 = time.time()

# Apply to the dataframe

df['Xest'] = calculate_Xestimate(df['Local_X'], df['v_Vel'],df['Direction'],df['T'])
df['Yest'] = calculate_Yestimate(df['Local_Y'], df['v_Vel'],df['Direction'],df['T'])


# Calculate the XtB and YtB
# df = df.sort_values('Vehicle_ID')
df['XtB'] = df.groupby('Vehicle_ID')['Local_X'].shift(-1)
df['YtB'] = df.groupby('Vehicle_ID')['Local_Y'].shift(-1)

# End time
end_time1 = time.time()
# Calculate the execution time
execution_time1 = end_time1 - start_time1

df = df.fillna(0)

# # Create the 'join_detection' column with values 1 for the first row of each Vehicle_ID
# df['join_detection'] = df.groupby('Vehicle_ID').cumcount() == 0

df['trust_score'] = pd.to_numeric(df['trust_score'])

print(df.head(10))

# # # Main calculation

def calculate_delta_estimate(Xest,Yest,X,Y):  # equation 5
  return abs(np.sqrt((Xest-X)**2 + (Yest-Y)**2))

def calculate_real_distance(XtB,YtB,X,Y): # equation 6
  return abs(np.sqrt((X-XtB)**2 + (Y-YtB)**2))

def update_trust_score_penalty(X,Y,Xest,Yest,XtB,YtB,epsilon,trust_score): # equation 6
    a = abs(calculate_delta_estimate(Xest,Yest,X,Y))
    b = abs(calculate_real_distance(XtB,YtB,X,Y))
    mask = abs(a - b) > epsilon
    # print(a)
    # print(b)
    # print(abs(a - b))
    # print(mask)
    return np.where(mask, trust_score - 5, trust_score) # apply the penalty label



    # checking and update trust_scrore

    # if penalty_label == 1:
    #   update trust_score : trust_score -= penalty
    #   checking trust_score with threshold
    #   adding the predicted label

# # # #  Calculate the trust_score_penalty # # #
# Create a copy of the DataFrame to store intermediate results
df_result = df.copy()

# starting the monitoring
tracemalloc.start()
process = psutil.Process(os.getpid())

start_time = time.time()
vehicle_id = 0
for index, row in df.iterrows():
    if index > 0:
        if vehicle_id != row['Vehicle_ID'] :
          prev_row = df_result.iloc[index - 1]
          a = abs(calculate_delta_estimate(row['Xest'], row['Yest'], row['Local_X'], row['Local_Y']))
          b = abs(calculate_real_distance(row['XtB'], row['YtB'], row['Local_X'], row['Local_Y']))
          if abs(a - b) + noiseSNR > epsilon:
              trust_score = prev_row['trust_score'] - penalty_point
              df_result.at[index, 'trust_score'] = trust_score
              if trust_score < trust_score_threshold:
                  vehicle_id = row['Vehicle_ID']


end_time = time.time()
print(tracemalloc.get_traced_memory())
total_cpu_percent = 0
num_samples = 0
interval = 0.5  # Adjust the interval based on your preference
min_samples = 5  # Set a minimum number of samples

while time.time() - start_time < (end_time - start_time) or num_samples < min_samples:
    cpu_percent = process.cpu_percent(interval=interval)
    total_cpu_percent += cpu_percent
    num_samples += 1

if num_samples > 0:
    average_cpu_percent = total_cpu_percent / num_samples
    print(f"Average CPU Usage: {average_cpu_percent:.6f}%")
else:
    print("No CPU usage data collected.")

# Drop intermediate columns
df = df_result.drop(columns=['Xest', 'Yest', 'Local_X', 'Local_Y', 'XtB', 'YtB'])


# Calculate the execution time
detection_time = end_time - start_time

print(df.head(10))

# Group by 'Vehicle_ID' and aggregate the 'label' as the first value and 'trust_score' as the minimum value
new_df = df.groupby('Vehicle_ID').agg({
    'label': 'first',
    'trust_score': 'min'
}).reset_index()

print(new_df.head(10))

# Function to calculate the predict_label based on trust_score
def calculate_predict_label(trust_score):
    return 1 if trust_score >= trust_score_threshold else 0

# Add the new predict_label column using apply and lambda function
new_df['predict_label'] = new_df['trust_score'].apply(lambda x: calculate_predict_label(x))

# value_counts = new_df['predict_label'].value_counts()
# print(value_counts)

# Calculate TP, TN, FP, FN
# 1: trusted
# 0: untrusted

TP = ((new_df['label'] == 1) & (new_df['predict_label'] == 1)).sum()
TN = ((new_df['label'] == 0) & (new_df['predict_label'] == 0)).sum()
FP = ((new_df['label'] == 0) & (new_df['predict_label'] == 1)).sum()
FN = ((new_df['label'] == 1) & (new_df['predict_label'] == 0)).sum()

# Calculate Accuracy
accuracy = (TP + TN) / (TP + TN + FP + FN)

# # # # Print the results
# Count the number of vehicle
number_of_vehicle  = df['Vehicle_ID'].nunique()
print("The total vehicle:", number_of_vehicle)
print('TP:', TP)
print('TN:', TN)
print('FP:', FP)
print('FN:', FN)
print('Accuracy:', accuracy)
print('SNR:', desired_snr_dB)
print('Epsilon:', epsilon_original)
print('Detection time:' + str(detection_time) + 'seconds')

import matplotlib.pyplot as plt

vehicle_counts = [1280, 1380, 1480, 1580, 1680]
accuracy_snr1 = [92.34, 92.46, 92.7, 92.53, 92.44 ]
accuracy_snr2 = [92.26, 92.32, 92.57, 92.32, 92.26]
accuracy_snr3 = [91.95, 91.88, 92.16, 92.09, 92.02]
accuracy_snr4 = [91.48, 91.38, 91.49, 91.39, 91.42]
accuracy_snr5 = [88.67, 88.91, 88.78, 88.73, 88.93]
accuracy_snr6 = [81.33, 82.1, 81.69, 81.96, 82.44]

# Plotting
plt.figure(figsize=(10, 6))

# Different markers for each SNR level
markers = ['o', 's', '^', 'D', 'p', '*']

plt.plot(vehicle_counts, accuracy_snr1, marker=markers[0], label="SNR = 30")
plt.plot(vehicle_counts, accuracy_snr2, marker=markers[1], label="SNR = 25")
plt.plot(vehicle_counts, accuracy_snr3, marker=markers[2], label="SNR = 20")
plt.plot(vehicle_counts, accuracy_snr4, marker=markers[3], label="SNR = 15")
plt.plot(vehicle_counts, accuracy_snr5, marker=markers[4], label="SNR = 10")
plt.plot(vehicle_counts, accuracy_snr6, marker=markers[5], label="SNR = 5")

# Customizations
plt.xlabel(r"Number of vehicles ($v_i$)", fontsize=20)  # Using LaTeX for subscript "i"
plt.ylabel("Accuracy (%)", fontsize=20)
plt.title("Accuracy vs. Number of Vehicles at different SNR levels", fontsize=20)
plt.grid(True, which='both', linestyle='--', linewidth=0.5)
plt.legend(fontsize=18, bbox_to_anchor=(0.9, 0.62))  # Custom position
plt.xticks(fontsize=16)
plt.yticks(fontsize=16)

# Display
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

# Data
noise_levels = [10, 15, 20, 25, 30]

# Hypothetical accuracy data for each combination of parameters
# The data structure represents accuracy for [epsilon1 with untrusted_vehicle_20%, epsilon2 with untrusted_vehicle_20%, epsilon1 with untrusted_vehicle_30%, epsilon2 with untrusted_vehicle_30%]
accuracy_data = [
    [92.32, 92.44, 92.44, 92.44, 92.44],
    [96.37, 96.49, 96.49, 96.6, 96.61],
    [92.74, 92.86, 92.86, 92.86, 92.86],
    [96.3, 96.43, 96.43, 96.55, 96.54]
]

# Plotting
plt.figure(figsize=(10, 6))

# Different markers for each combination
markers = ['o', 's', '^', 'D']
labels = [
    "ε=1, Untrusted=20%",
    "ε=2, Untrusted=20%",
    "ε=1, Untrusted=30%",
    "ε=2, Untrusted=30%"
]

for i, (marker, label) in enumerate(zip(markers, labels)):
    plt.plot(noise_levels, accuracy_data[i], marker=marker, label=label, markersize=10, linewidth=3)

# Customizations
plt.xlabel("Percentage of noise added (%)", fontsize=20)
plt.ylabel("Accuracy (%)", fontsize=20)
plt.title("Accuracy vs. Noise Levels at different parameters", fontsize=20)
plt.grid(True, which='both', linestyle='--', linewidth=0.5)
plt.legend(fontsize=18, bbox_to_anchor=(0.5, 0.3))

plt.xticks(fontsize=16)
plt.yticks(fontsize=16)

# Display
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

# Data
untrusted_vehicles = [10, 15, 20, 25, 30]

# Hypothetical accuracy data for each epsilon value (excluding epsilon 0.5)
# The data structure represents accuracy for [epsilon 1, epsilon 2, epsilon 5]
accuracy_data = [
    [91.07, 92.26, 92.32, 92.44, 92.74],
    [95.48, 96.42, 96.37, 96.37, 96.3],
    [95.83, 96.72, 96.6, 96.61, 96.43]
]

# Plotting
plt.figure(figsize=(10, 6))

# Different markers for each epsilon value
markers = ['s', '^', 'D']
epsilons = [1, 2, 5]
labels = [f"ε={epsilon}" for epsilon in epsilons]

for i, (marker, label) in enumerate(zip(markers, labels)):
    plt.plot(untrusted_vehicles, accuracy_data[i], marker=marker, label=label, markersize=10, linewidth=3)

# Customizations
plt.xlabel("Untrusted Vehicles (%)", fontsize=20)
plt.ylabel("Accuracy (%)", fontsize=20)
plt.title("Accuracy vs. Untrusted Vehicles at different Epsilon (ε) values", fontsize=20)
plt.grid(True, which='both', linestyle='--', linewidth=0.5)
plt.legend(fontsize=30, bbox_to_anchor=(0.9, 0.6))

plt.xticks(fontsize=16)
plt.yticks(fontsize=16)

# Display
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

# Given data
x = [1280, 1380, 1480, 1580, 1680]
y = [19.077, 19.605, 20.291, 21.365, 22.91]

# Create a combined bar and line plot
plt.figure(figsize=(10, 6))

# Create the bar graph
plt.bar(x, y, color='skyblue', label='Average Detection Time', width=40)

# Create the line plot
plt.plot(x, y, '-o', color='blue', linewidth=3, markersize=10, label='Trend Line')

plt.title("Average Detection Time vs. Number of Vehicles", fontsize=20)
plt.xlabel(r"Number of vehicles ($v_i$)", fontsize=20)
plt.ylabel("Average Detection Time (seconds)", fontsize=20)
plt.grid(True, which='both', linestyle='--', linewidth=0.5, axis='y')
plt.legend(fontsize=16, bbox_to_anchor=(0.4, 0.82))

plt.xticks(fontsize=16)
plt.yticks(fontsize=16)

# Display the plot
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

# Given data
x = [1280, 1380, 1480, 1580, 1680]
y = [52105910, 54687815, 57772685, 60519638, 63735601]

# Create a combined bar and line plot
plt.figure(figsize=(10, 6))

# Plotting
plt.bar(x, y, color='darkgreen', width=40)
plt.plot(x, y, color='red', marker='o')

plt.xlabel(r"Number of vehicles ($v_i$)", fontsize=20)
plt.ylabel('Memory Usage (KiB)', fontsize=20)
plt.title('Memory Usage vs Number of Vehicles', fontsize=20)
plt.grid(True)
plt.xticks(fontsize=16)
plt.yticks(fontsize=16)

plt.show()

import matplotlib.pyplot as plt

# Given data
x = [1280, 1380, 1480, 1580, 1680]
y = [0.6, 0.6, 0.6, 0.6, 0.6]

# Create a combined bar and line plot
plt.figure(figsize=(10, 6))

# Plotting
plt.bar(x, y, color='indigo', width=40)
plt.plot(x, y, color='chocolate', marker='o')

plt.xlabel(r"Number of vehicles ($v_i$)", fontsize=20)
plt.ylabel('CPU Usage (%)', fontsize=20)
plt.title('CPU Usage vs Number of Vehicles', fontsize=20)
plt.grid(True)
plt.xticks(fontsize=16)
plt.yticks(fontsize=16)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Data for the second graph
num_vehicles = ['1280', '1380', '1480', '1580', '1680']
accuracy_41_vehicles = [75, 77, 79, 81, 83]
accuracy_42_vehicles = [70, 72, 74, 76, 78]
accuracy_43_vehicles = [65, 67, 69, 71, 73]
accuracy_our_method_vehicles = [85, 87, 89, 91, 93]

# Plotting the second graph with adjusted style and additional formatting
fig, ax = plt.subplots(figsize=(10, 6))
bar_width = 0.2
index = np.arange(len(num_vehicles))

bar1 = plt.bar(index, accuracy_41_vehicles, bar_width, hatch='o', edgecolor='black', color='#b5dbe8', label='[43]')
bar2 = plt.bar(index + bar_width, accuracy_42_vehicles, bar_width, hatch='/', edgecolor='black', color='#bbd7b9', label='[44]')
bar3 = plt.bar(index + 2 * bar_width, accuracy_43_vehicles, bar_width, hatch='.', edgecolor='black', color='#fbbbb6', label='[45]')
bar4 = plt.bar(index + 3 * bar_width, accuracy_our_method_vehicles, bar_width, hatch='x', edgecolor='black', color='#ffdfd6', label='Our Method')

plt.xlabel('Number of Vehicles', fontsize=26)
plt.ylabel('Accuracy (%)', fontsize=26)
plt.xticks(index + 1.5 * bar_width, num_vehicles, fontsize=18)
plt.yticks(fontsize=18)

plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', fontsize=20)
# plt.grid(True)
# plt.tight_layout(rect=[0, 0, 0.85, 1])  # Adjusting the layout to fit the legend outside the plot
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Data for the second graph
num_vehicles = ['1280', '1380', '1480', '1580', '1680']
accuracy_41_vehicles = [75, 77, 79, 81, 83]
accuracy_42_vehicles = [70, 72, 74, 76, 78]
accuracy_43_vehicles = [65, 67, 69, 71, 73]
accuracy_our_method_vehicles = [85, 87, 89, 91, 93]

# Plotting the second graph with adjusted style and additional formatting
fig, ax = plt.subplots(figsize=(10, 6))
bar_width = 0.2
index = np.arange(len(num_vehicles))

bar1 = plt.bar(index, accuracy_41_vehicles, bar_width, hatch='//', edgecolor='black', color='#f2eff6', label='[43]')
bar2 = plt.bar(index + bar_width, accuracy_42_vehicles, bar_width, hatch='\\\\', edgecolor='black', color='#c3cee4', label='[44]')
bar3 = plt.bar(index + 2 * bar_width, accuracy_43_vehicles, bar_width, hatch='xx', edgecolor='black', color='#82b1d3', label='[45]')
bar4 = plt.bar(index + 3 * bar_width, accuracy_our_method_vehicles, bar_width, hatch='oo', edgecolor='black', color='#4097c4', label='Our Method')

plt.xlabel('Number of Vehicles', fontsize=26)
plt.ylabel('Accuracy (%)', fontsize=26)
plt.xticks(index + 1.5 * bar_width, num_vehicles, fontsize=18)
plt.yticks(fontsize=18)

plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', fontsize=20)
# plt.grid(True)
# plt.tight_layout(rect=[0, 0, 0.85, 1])  # Adjusting the layout to fit the legend outside the plot
plt.show()

# ============================================================
# EXTRA BLOCK: Comparison with baseline derived from [
# Add this block at the END of the file
# ============================================================

import numpy as np
import pandas as pd
import math

def compute_metrics(y_true, y_pred):
    """
    Metrics with malicious-as-positive convention:
    malicious = 1, benign/trusted = 0
    """
    y_true = np.array(y_true).astype(int)
    y_pred = np.array(y_pred).astype(int)

    TP = int(((y_true == 1) & (y_pred == 1)).sum())
    TN = int(((y_true == 0) & (y_pred == 0)).sum())
    FP = int(((y_true == 0) & (y_pred == 1)).sum())
    FN = int(((y_true == 1) & (y_pred == 0)).sum())

    accuracy = (TP + TN) / (TP + TN + FP + FN) if (TP + TN + FP + FN) else 0.0
    tpr = TP / (TP + FN) if (TP + FN) else 0.0
    tnr = TN / (TN + FP) if (TN + FP) else 0.0
    fpr = FP / (FP + TN) if (FP + TN) else 0.0
    precision = TP / (TP + FP) if (TP + FP) else 0.0
    recall = tpr
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) else 0.0

    return {
        "TP": TP,
        "TN": TN,
        "FP": FP,
        "FN": FN,
        "Accuracy": accuracy,
        "TPR": tpr,
        "TNR": tnr,
        "FPR": fpr,
        "Precision": precision,
        "Recall": recall,
        "F1": f1
    }


def run_baseline_from_2(df_input,
                        trust_threshold=85,
                        reward_point=1,
                        penalty_point=5,
                        epsilon=1):
    """
    Trajectory-compatible baseline inspired by [2].
    Keeps a fixed reward / penalty reputation update style.
    Assumes df_input contains:
        Vehicle_ID, Global_Time, Local_X, Local_Y, Xest, Yest, XtB, YtB, label
    label convention in existing code:
        1 = trusted
        0 = untrusted
    """
    df_base = df_input.copy()

    # Initialize score
    df_base['baseline_score'] = 100

    # Predicted / actual motion gap
    delta_est = np.sqrt((df_base['Xest'] - df_base['Local_X'])**2 +
                        (df_base['Yest'] - df_base['Local_Y'])**2)

    delta_real = np.sqrt((df_base['Local_X'] - df_base['XtB'])**2 +
                         (df_base['Local_Y'] - df_base['YtB'])**2)

    # Event: plausible => reward, implausible => penalty
    df_base['baseline_event'] = np.where(
        np.abs(delta_est - delta_real) > epsilon,
        -penalty_point,
        reward_point
    )

    # Accumulate score by vehicle
    baseline_rows = []
    for vid, g in df_base.groupby('Vehicle_ID'):
        g = g.sort_values('Global_Time').copy()
        g['baseline_score'] = 100 + g['baseline_event'].cumsum()
        baseline_rows.append(g)

    df_base = pd.concat(baseline_rows, ignore_index=True)

    # Vehicle-level aggregation
    baseline_vehicle = df_base.groupby('Vehicle_ID').agg({
        'label': 'first',
        'baseline_score': 'min'
    }).reset_index()

    # Existing convention:
    # predict_label = 1 if trusted, 0 if untrusted
    baseline_vehicle['predict_label_baseline'] = np.where(
        baseline_vehicle['baseline_score'] >= trust_threshold, 1, 0
    )

    return baseline_vehicle


print("\n" + "=" * 60)
print("STARTING EXTRA COMPARISON WITH BASELINE [2]")
print("=" * 60)

# ----------------------------------------------------------------
# 1) Rebuild the intermediate dataframe needed by the baseline
# ----------------------------------------------------------------
# We reconstruct from the same source data so the comparison is fair.
df_compare = pd.read_csv('/content/drive/MyDrive/labtest/vehicle_data_full.csv')
df_compare = pd.DataFrame(df_compare)

# Match the same truncation rule used in the original code
df_compare = df_compare.groupby('Vehicle_ID').head(100)

# Reset index safely
df_compare.set_index('Vehicle_ID', inplace=True)
df_compare.reset_index(inplace=True)

# Keep same parameters as the original run
# percentage_of_untrusted_vehicle, Gaussian_percentage, epsilon,
# trust_score_threshold, penalty_point are assumed to already exist above

# Initialize labels using the same logic as the original code
df_compare['label'] = 1

untrust_df_compare = pd.read_csv('/content/drive/MyDrive/labtest/vehicle_data.csv')
untrust_df_compare = pd.DataFrame(untrust_df_compare)

number_of_vehicle_compare = df_compare['Vehicle_ID'].nunique()
number_of_untrusted_compare = int(percentage_of_untrusted_vehicle / 100 * number_of_vehicle_compare)

selected_column_compare = untrust_df_compare['Vehicle_ID'].head(number_of_untrusted_compare)
array_id_vehicle_anomalies_compare = selected_column_compare.values

df_compare.loc[df_compare['Vehicle_ID'].isin(array_id_vehicle_anomalies_compare), 'label'] = 0

# Inject the same kind of noise used in the original code
noise_x = df_compare.loc[df_compare['label'] == 0, 'Local_X'] * Gaussian_percentage
noise_y = df_compare.loc[df_compare['label'] == 0, 'Local_Y'] * Gaussian_percentage

df_compare.loc[df_compare['label'] == 0, 'Local_X'] += np.abs(noise_x)
df_compare.loc[df_compare['label'] == 0, 'Local_Y'] += np.abs(noise_y)

# Ensure Direction mapping matches the original code
mapping_compare = {1: 90, 2: 180, 3: 270, 4: 360}
df_compare['Direction'] = df_compare['Direction'].map(mapping_compare)

# Recompute T if needed
if 'T' not in df_compare.columns:
    df_compare = df_compare.sort_values(by=['Vehicle_ID', 'Global_Time'])
    df_compare['T'] = df_compare.groupby('Vehicle_ID')['Global_Time'].shift(-1) - df_compare['Global_Time']
    df_compare['T'] = df_compare['T'] * 0.001

# Recompute Xest / Yest / XtB / YtB
df_compare['Xest'] = calculate_Xestimate(df_compare['Local_X'], df_compare['v_Vel'], df_compare['Direction'], df_compare['T'])
df_compare['Yest'] = calculate_Yestimate(df_compare['Local_Y'], df_compare['v_Vel'], df_compare['Direction'], df_compare['T'])

df_compare['XtB'] = df_compare.groupby('Vehicle_ID')['Local_X'].shift(-1)
df_compare['YtB'] = df_compare.groupby('Vehicle_ID')['Local_Y'].shift(-1)

df_compare = df_compare.fillna(0)

# ----------------------------------------------------------------
# 2) Run baseline derived from [2]
# ----------------------------------------------------------------
baseline_vehicle_df = run_baseline_from_2(
    df_input=df_compare,
    trust_threshold=trust_score_threshold,
    reward_point=1,
    penalty_point=penalty_point,
    epsilon=epsilon
)

# ----------------------------------------------------------------
# 3) Prepare OUR METHOD results from existing dataframe `new_df`
#    Existing code already built:
#       new_df['label']
#       new_df['predict_label']
#    with convention: 1=trusted, 0=untrusted
# ----------------------------------------------------------------
our_vehicle_df = new_df.copy()

# Convert both methods to malicious-as-positive:
# original label: trusted=1, untrusted=0
# malicious label: malicious=1, benign=0
our_vehicle_df['mal_label'] = np.where(our_vehicle_df['label'] == 0, 1, 0)
our_vehicle_df['mal_pred'] = np.where(our_vehicle_df['predict_label'] == 0, 1, 0)

baseline_vehicle_df['mal_label'] = np.where(baseline_vehicle_df['label'] == 0, 1, 0)
baseline_vehicle_df['mal_pred'] = np.where(baseline_vehicle_df['predict_label_baseline'] == 0, 1, 0)

# ----------------------------------------------------------------
# 4) Compute metrics
# ----------------------------------------------------------------
our_metrics = compute_metrics(
    our_vehicle_df['mal_label'].tolist(),
    our_vehicle_df['mal_pred'].tolist()
)

baseline_metrics = compute_metrics(
    baseline_vehicle_df['mal_label'].tolist(),
    baseline_vehicle_df['mal_pred'].tolist()
)

# ----------------------------------------------------------------
# 5) Print detailed metrics
# ----------------------------------------------------------------
print("\n========== OUR METHOD (Edge-MDS) ==========")
for k, v in our_metrics.items():
    if isinstance(v, float):
        print(f"{k}: {v:.4f}")
    else:
        print(f"{k}: {v}")

print("\n========== BASELINE FROM [2] ==========")
for k, v in baseline_metrics.items():
    if isinstance(v, float):
        print(f"{k}: {v:.4f}")
    else:
        print(f"{k}: {v}")

# ----------------------------------------------------------------
# 6) Summary table in percentage
# ----------------------------------------------------------------
summary_df = pd.DataFrame([
    {
        'Method': 'Edge-MDS',
        'Accuracy (%)': our_metrics['Accuracy'] * 100,
        'TPR (%)': our_metrics['TPR'] * 100,
        'TNR (%)': our_metrics['TNR'] * 100,
        'FPR (%)': our_metrics['FPR'] * 100,
        'Precision (%)': our_metrics['Precision'] * 100,
        'Recall (%)': our_metrics['Recall'] * 100,
        'F1 (%)': our_metrics['F1'] * 100
    },
    {
        'Method': 'Baseline [2]',
        'Accuracy (%)': baseline_metrics['Accuracy'] * 100,
        'TPR (%)': baseline_metrics['TPR'] * 100,
        'TNR (%)': baseline_metrics['TNR'] * 100,
        'FPR (%)': baseline_metrics['FPR'] * 100,
        'Precision (%)': baseline_metrics['Precision'] * 100,
        'Recall (%)': baseline_metrics['Recall'] * 100,
        'F1 (%)': baseline_metrics['F1'] * 100
    }
])

print("\n========== SUMMARY TABLE ==========")
print(summary_df.round(2))

# Save CSV for paper writing
summary_path = '/content/drive/MyDrive/labtest/summary_compare_with_2.csv'
summary_df.to_csv(summary_path, index=False)
print(f"\nSaved summary table to: {summary_path}")

# Optional: save detailed vehicle-level outputs
our_vehicle_df.to_csv('/content/drive/MyDrive/labtest/our_method_vehicle_level.csv', index=False)
baseline_vehicle_df.to_csv('/content/drive/MyDrive/labtest/baseline_2_vehicle_level.csv', index=False)

print("\nComparison block completed.")
print("=" * 60)